import { Lato, Open_Sans } from "next/font/google";
import "@/app/styles/style.sass";
import Header from "./component/Header";
import Footer from "./component/Footer";

const lato = Lato({
  subsets: ["latin"],
  weight: ["400", "700", "900"],
  variable: "--font-lato",
});

const openSans = Open_Sans({
  subsets: ["latin"],
  variable: "--font-open-sans",
});

export const metadata = {
  title: "Headless CMS",
  description: "Generated by Ankush Yadev",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${openSans.className} ${openSans.variable} ${lato.variable}`}
      >
        <Header/>
        {children}
        <Footer/>
      </body>
    </html>
  );
}
